version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=database
  test:
    image: oven/bun
    command: bun run index.ts
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
